# Generated by Django 5.1.4 on 2025-04-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_scanner.container'),
        ),
    ]
