# Generated by Django 5.1.4 on 2025-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_scanner', '0002_alter_item_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
